// ISO 3166-1 alpha-2 → fr/en name table for common countries.
// Used to: (a) auto-derive countryCode from a country name typed in the
// admin form, (b) auto-create Country rows when a new code is seen.

export const COUNTRY_NAMES: Record<string, { fr: string; en: string }> = {
  AD: { fr: 'Andorre', en: 'Andorra' },
  AE: { fr: 'Émirats arabes unis', en: 'United Arab Emirates' },
  AF: { fr: 'Afghanistan', en: 'Afghanistan' },
  AG: { fr: 'Antigua-et-Barbuda', en: 'Antigua and Barbuda' },
  AL: { fr: 'Albanie', en: 'Albania' },
  AM: { fr: 'Arménie', en: 'Armenia' },
  AO: { fr: 'Angola', en: 'Angola' },
  AR: { fr: 'Argentine', en: 'Argentina' },
  AT: { fr: 'Autriche', en: 'Austria' },
  AU: { fr: 'Australie', en: 'Australia' },
  AZ: { fr: 'Azerbaïdjan', en: 'Azerbaijan' },
  BA: { fr: 'Bosnie-Herzégovine', en: 'Bosnia and Herzegovina' },
  BB: { fr: 'Barbade', en: 'Barbados' },
  BD: { fr: 'Bangladesh', en: 'Bangladesh' },
  BE: { fr: 'Belgique', en: 'Belgium' },
  BG: { fr: 'Bulgarie', en: 'Bulgaria' },
  BH: { fr: 'Bahreïn', en: 'Bahrain' },
  BJ: { fr: 'Bénin', en: 'Benin' },
  BO: { fr: 'Bolivie', en: 'Bolivia' },
  BR: { fr: 'Brésil', en: 'Brazil' },
  BS: { fr: 'Bahamas', en: 'Bahamas' },
  BT: { fr: 'Bhoutan', en: 'Bhutan' },
  BW: { fr: 'Botswana', en: 'Botswana' },
  BY: { fr: 'Biélorussie', en: 'Belarus' },
  BZ: { fr: 'Belize', en: 'Belize' },
  CA: { fr: 'Canada', en: 'Canada' },
  CG: { fr: 'République du Congo', en: 'Republic of the Congo' },
  CH: { fr: 'Suisse', en: 'Switzerland' },
  CI: { fr: "Côte d'Ivoire", en: "Côte d'Ivoire" },
  CL: { fr: 'Chili', en: 'Chile' },
  CM: { fr: 'Cameroun', en: 'Cameroon' },
  CN: { fr: 'Chine', en: 'China' },
  CO: { fr: 'Colombie', en: 'Colombia' },
  CR: { fr: 'Costa Rica', en: 'Costa Rica' },
  CU: { fr: 'Cuba', en: 'Cuba' },
  CV: { fr: 'Cap-Vert', en: 'Cape Verde' },
  CY: { fr: 'Chypre', en: 'Cyprus' },
  CZ: { fr: 'Tchéquie', en: 'Czechia' },
  DE: { fr: 'Allemagne', en: 'Germany' },
  DK: { fr: 'Danemark', en: 'Denmark' },
  DO: { fr: 'République dominicaine', en: 'Dominican Republic' },
  DZ: { fr: 'Algérie', en: 'Algeria' },
  EC: { fr: 'Équateur', en: 'Ecuador' },
  EE: { fr: 'Estonie', en: 'Estonia' },
  EG: { fr: 'Égypte', en: 'Egypt' },
  ES: { fr: 'Espagne', en: 'Spain' },
  ET: { fr: 'Éthiopie', en: 'Ethiopia' },
  FI: { fr: 'Finlande', en: 'Finland' },
  FJ: { fr: 'Fidji', en: 'Fiji' },
  FR: { fr: 'France', en: 'France' },
  GA: { fr: 'Gabon', en: 'Gabon' },
  GB: { fr: 'Royaume-Uni', en: 'United Kingdom' },
  GE: { fr: 'Géorgie', en: 'Georgia' },
  GH: { fr: 'Ghana', en: 'Ghana' },
  GR: { fr: 'Grèce', en: 'Greece' },
  GT: { fr: 'Guatemala', en: 'Guatemala' },
  GY: { fr: 'Guyana', en: 'Guyana' },
  HK: { fr: 'Hong Kong', en: 'Hong Kong' },
  HN: { fr: 'Honduras', en: 'Honduras' },
  HR: { fr: 'Croatie', en: 'Croatia' },
  HT: { fr: 'Haïti', en: 'Haiti' },
  HU: { fr: 'Hongrie', en: 'Hungary' },
  ID: { fr: 'Indonésie', en: 'Indonesia' },
  IE: { fr: 'Irlande', en: 'Ireland' },
  IL: { fr: 'Israël', en: 'Israel' },
  IN: { fr: 'Inde', en: 'India' },
  IR: { fr: 'Iran', en: 'Iran' },
  IS: { fr: 'Islande', en: 'Iceland' },
  IT: { fr: 'Italie', en: 'Italy' },
  JM: { fr: 'Jamaïque', en: 'Jamaica' },
  JO: { fr: 'Jordanie', en: 'Jordan' },
  JP: { fr: 'Japon', en: 'Japan' },
  KE: { fr: 'Kenya', en: 'Kenya' },
  KH: { fr: 'Cambodge', en: 'Cambodia' },
  KR: { fr: 'Corée du Sud', en: 'South Korea' },
  KW: { fr: 'Koweït', en: 'Kuwait' },
  KZ: { fr: 'Kazakhstan', en: 'Kazakhstan' },
  LA: { fr: 'Laos', en: 'Laos' },
  LB: { fr: 'Liban', en: 'Lebanon' },
  LK: { fr: 'Sri Lanka', en: 'Sri Lanka' },
  LT: { fr: 'Lituanie', en: 'Lithuania' },
  LU: { fr: 'Luxembourg', en: 'Luxembourg' },
  LV: { fr: 'Lettonie', en: 'Latvia' },
  LY: { fr: 'Libye', en: 'Libya' },
  MA: { fr: 'Maroc', en: 'Morocco' },
  MC: { fr: 'Monaco', en: 'Monaco' },
  MD: { fr: 'Moldavie', en: 'Moldova' },
  ME: { fr: 'Monténégro', en: 'Montenegro' },
  MG: { fr: 'Madagascar', en: 'Madagascar' },
  MK: { fr: 'Macédoine du Nord', en: 'North Macedonia' },
  ML: { fr: 'Mali', en: 'Mali' },
  MM: { fr: 'Birmanie', en: 'Myanmar' },
  MN: { fr: 'Mongolie', en: 'Mongolia' },
  MT: { fr: 'Malte', en: 'Malta' },
  MU: { fr: 'Maurice', en: 'Mauritius' },
  MV: { fr: 'Maldives', en: 'Maldives' },
  MX: { fr: 'Mexique', en: 'Mexico' },
  MY: { fr: 'Malaisie', en: 'Malaysia' },
  MZ: { fr: 'Mozambique', en: 'Mozambique' },
  NA: { fr: 'Namibie', en: 'Namibia' },
  NG: { fr: 'Nigeria', en: 'Nigeria' },
  NI: { fr: 'Nicaragua', en: 'Nicaragua' },
  NL: { fr: 'Pays-Bas', en: 'Netherlands' },
  NO: { fr: 'Norvège', en: 'Norway' },
  NP: { fr: 'Népal', en: 'Nepal' },
  NZ: { fr: 'Nouvelle-Zélande', en: 'New Zealand' },
  OM: { fr: 'Oman', en: 'Oman' },
  PA: { fr: 'Panama', en: 'Panama' },
  PE: { fr: 'Pérou', en: 'Peru' },
  PH: { fr: 'Philippines', en: 'Philippines' },
  PK: { fr: 'Pakistan', en: 'Pakistan' },
  PL: { fr: 'Pologne', en: 'Poland' },
  PT: { fr: 'Portugal', en: 'Portugal' },
  PY: { fr: 'Paraguay', en: 'Paraguay' },
  QA: { fr: 'Qatar', en: 'Qatar' },
  RO: { fr: 'Roumanie', en: 'Romania' },
  RS: { fr: 'Serbie', en: 'Serbia' },
  RU: { fr: 'Russie', en: 'Russia' },
  RW: { fr: 'Rwanda', en: 'Rwanda' },
  SA: { fr: 'Arabie saoudite', en: 'Saudi Arabia' },
  SE: { fr: 'Suède', en: 'Sweden' },
  SG: { fr: 'Singapour', en: 'Singapore' },
  SI: { fr: 'Slovénie', en: 'Slovenia' },
  SK: { fr: 'Slovaquie', en: 'Slovakia' },
  SN: { fr: 'Sénégal', en: 'Senegal' },
  SR: { fr: 'Suriname', en: 'Suriname' },
  SY: { fr: 'Syrie', en: 'Syria' },
  TG: { fr: 'Togo', en: 'Togo' },
  TH: { fr: 'Thaïlande', en: 'Thailand' },
  TN: { fr: 'Tunisie', en: 'Tunisia' },
  TR: { fr: 'Turquie', en: 'Turkey' },
  TT: { fr: 'Trinité-et-Tobago', en: 'Trinidad and Tobago' },
  TW: { fr: 'Taïwan', en: 'Taiwan' },
  TZ: { fr: 'Tanzanie', en: 'Tanzania' },
  UA: { fr: 'Ukraine', en: 'Ukraine' },
  UG: { fr: 'Ouganda', en: 'Uganda' },
  US: { fr: 'États-Unis', en: 'United States' },
  UY: { fr: 'Uruguay', en: 'Uruguay' },
  UZ: { fr: 'Ouzbékistan', en: 'Uzbekistan' },
  VE: { fr: 'Venezuela', en: 'Venezuela' },
  VN: { fr: 'Vietnam', en: 'Vietnam' },
  YE: { fr: 'Yémen', en: 'Yemen' },
  ZA: { fr: 'Afrique du Sud', en: 'South Africa' },
  ZM: { fr: 'Zambie', en: 'Zambia' },
  ZW: { fr: 'Zimbabwe', en: 'Zimbabwe' },
};

function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]/g, '');
}

/**
 * Resolve a country name (fr or en) to its alpha-2 code.
 * Returns null if not found.
 */
export function nameToCode(name: string | null | undefined): string | null {
  if (!name) return null;
  const n = normalize(name);
  for (const [code, names] of Object.entries(COUNTRY_NAMES)) {
    if (normalize(names.fr) === n || normalize(names.en) === n) return code;
  }
  return null;
}
